<?php
/** @var $block \AristanderAi\Aai\Block\PageView\Data */

$event = $block->getPageRecorder()->exportEvent();
if (!$event) {
    // Event record disabled
    return;
}
?>
<script type="text/x-magento-init">
{
    "*": {
        "AristanderAi_Aai/js/track-page": <?= json_encode([
            'url' => $block->getTrackUrl(),
            'details' => $event->getDetails(),
        ]) ?>
    }
}
</script>
