<?php
/** @var $block \AristanderAi\Aai\Block\PageView\Data */

$event = $block->getPageRecorder()->exportEvent();
if (!$event) {
    // Event record disabled
    return;
}
?>
<script type="text/x-magento-init">
{
    "*": {
        "AristanderAi_Aai/js/track-page": {
            "url": "<?= $block->escapeJs($block->getTrackUrl()) ?>",
            "details": "<?= $block->escapeJs(base64_encode(serialize($event->getDetails()))) ?>"
        }
    }
}
</script>