<?php
/** @var $block \AristanderAi\Aai\Block\Adminhtml\System\Config\RestorePrices */
?>
<div class="aai-restore-prices"
>
    <button type="button"
            class="aai-action--restore-prices disabled"
            disabled
    >Restore Original Prices</button>
    <p class="note aai-restore-prices--notice--no-backup">
        <?= $block->escapeHtml(__('No prices were replaced yet')) ?>
    </p>
</div>