<?php
/** @var $block \AristanderAi\Aai\Block\Adminhtml\System\Config\RestorePrices */
?>
<script type="text/x-magento-init">
    {
        "*": {
            "AristanderAi_Aai/js/restore-prices": {
                "ajax-url": "<?= $block->escapeJs($block->getActionUrl()) ?>",
                "messages": {
                    "confirm": "<?= $block->escapeJs(__(
                        'Are you sure you want to restore all prices from backup?'
                    )) ?>",
                    "success": "<?= $block->escapeJs(__(
                        'All prices were restored from backup'
                    )) ?>",
                    "error": "<?= $block->escapeJs(__(
                        'Error restoring prices. Please contact Aristander.ai support.'
                    )) ?>"
                }
            }
        }
    }
</script>
<div class="aai-restore-prices js-aai-restore-prices">
    <button type="button"
            class="aai-restore-prices--button js-aai-restore-prices--button"
    ><?= $block->escapeHtml(__('Restore Original Prices')) ?></button>
    <?php if ('progress' == $block->getStatus()): ?>
        <p class="note js-aai-remove-on-start aai-restore-prices--notice--interrupted">
            <?= nl2br($block->escapeHtml(__(<<<'TAG'
Restoration process was interrupted. Please click Restore Original Prices to continue.
Do not close this page until finished.
TAG
            ))) ?>
        </p>
    <?php endif ?>
</div>