<?php
/** @var $block \AristanderAi\Aai\Block\Adminhtml\System\Config\RestorePrices */
?>
<script type="text/x-magento-init">
    {
        "*": {
            "AristanderAi_Aai/js/restore-prices": {}
        }
    }
</script>
<div class="aai-restore-prices">
    <button type="button"
            class="aai-restore-prices--button js-aai-restore-prices--button"
    ><?= $block->escapeHtml(__('Disable Aristander')) ?></button>
</div>