<?php
/** @var $block \AristanderAi\Aai\Block\Adminhtml\System\Config\Visualization */
?>
<a class="aai-visualization--image--link"
   href="<?= $block->escapeHtml($block->getLinkUrl()) ?>"
   target="_blank"
>
    <img class="aai-visualization--image"
         src="<?= $block->escapeHtml($block->getImageUrl()) ?>"
         alt="Visualization"
    >
</a>
<div class="aai-visualization--toolbar">
    <a class="action-primary"
       href="<?= $block->escapeHtml($block->getLinkUrl()) ?>"
       target="_blank"
    >View</a>
</div>